schema_version: 1
seed: 1639767175
global:
  mutation_rate: 0.02
templates:
  t:
    type: HOR_slots
    monomer_length_bp: 171
    k: 12
    inter_slot_divergence: 0.15
structure:
  - type: HOR
    template: t
    n_copies: 300
post_generation:
  - type: INVERSION
    block: 0
    start_copy: 10
    length_copies: 1
