schema_version: 1
seed: 780818197
global:
  mutation_rate: 0.02
templates:
  m:
    type: monomer
    monomer_length_bp: 1000
    gc_content: 0.2
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 1000
