schema_version: 1
seed: 260980641
global:
  mutation_rate: 0.02
templates:
  m:
    type: monomer
    monomer_length_bp: 500
    gc_content: 0.3
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 1000
