schema_version: 1
seed: 2525621815
global:
  mutation_rate: 0.02
templates:
  m:
    type: monomer
    monomer_length_bp: 170
    gc_content: 0.8
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 500
