schema_version: 1
seed: 177943105
global:
  mutation_rate: 0.01
  indel_rate: 0.0
templates:
  m:
    type: monomer
    monomer_length_bp: 100
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 2000
