schema_version: 1
seed: 1161070187
global:
  mutation_rate: 0.01
  indel_rate: 0.01
templates:
  m:
    type: monomer
    monomer_length_bp: 170
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 1000
