schema_version: 1
seed: 120429038
global:
  mutation_rate: 0.02
  indel_rate: 0.0
templates:
  m:
    type: monomer
    monomer_length_bp: 100
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 1000
