schema_version: 1
seed: 876467469
global:
  mutation_rate: 0.02
  indel_rate: 0.0
templates:
  m:
    type: monomer
    monomer_length_bp: 250
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 2000
