schema_version: 1
seed: 1640888331
global:
  mutation_rate: 0.05
  indel_rate: 0.01
templates:
  m:
    type: monomer
    monomer_length_bp: 1000
structure:
  - type: SIMPLE_TR
    template: m
    n_copies: 500
