schema_version: 1
seed: 1552671625
global:
  mutation_rate: 0.02
templates:
  t:
    type: HOR_slots
    monomer_length_bp: 250
    k: 12
    inter_slot_divergence: 0.15
structure:
  - type: HOR
    template: t
    n_copies: 50
  - type: SHIFT
    offset_bp: 100
  - type: HOR
    template: t
    n_copies: 50
