schema_version: 1
seed: 874564506
global:
  mutation_rate: 0.02
templates:
  t:
    type: HOR_slots
    monomer_length_bp: 171
    k: 6
    inter_slot_divergence: 0.15
structure:
  - type: HOR
    template: t
    n_copies: 25
  - type: SHIFT
    offset_bp: 25
  - type: HOR
    template: t
    n_copies: 25
